APP=deformaciones
MAIN=main
OS := $(shell uname -s)

ifeq ($(OS), Linux)
run: build
	sudo ./${APP}
endif
ifeq ($(OS), Darwin)
run: build
	./${APP}.app/Contents/MacOS/${APP}
endif

build: Makefile ./**/*.cpp ./*.cpp ./**/*.h ./*.h
	make

Makefile: ${MAIN}.pro
	qmake ${MAIN}.pro

clean:
	rm .qmake.stash
	rm *.o
	rm moc_*
	rm Makefile
	rm ${APP} | rm -r ${APP}.app