######################################################################
# Automatically generated by qmake (1.07a) Wed Oct 6 11:42:48 2004
######################################################################

TEMPLATE = app
TARGET		= cubo
INCLUDEPATH += .
# ¿Es necesario incluir este camino? :
INCLUDEPATH += "/usr/X11/include"


QT += opengl

# Input
HEADERS += painter.h canvas.h cubo.h reguilete.h
SOURCES += main.cpp painter.cpp canvas.cpp cubo.cpp reguilete.cpp
QMAKE_CXXFLAGS += -std=c++11
