######################################################################
# Automatically generated by qmake (1.07a) Wed Oct 6 11:42:48 2004
######################################################################

TEMPLATE = app
TARGET		= cubo
INCLUDEPATH += .
# ¿Es necesario incluir este camino? :
INCLUDEPATH += "/usr/X11/include"


QT += opengl

# Input
HEADERS += painter.h cubo.h
SOURCES += main.cpp painter.cpp cubo.cpp
