APP=cubo

run: ${APP}.app/Contents/MacOS/${APP}
	./${APP}.app/Contents/MacOS/${APP}
${APP}.app/Contents/MacOS/${APP}: Makefile *.cpp *.h
	make
Makefile: ${APP}.pro
	qmake ${APP}.pro
clean:
	rm -rf ./*.o ./.*.stash ./*.app Makefile