APP=deformaciones
EXT=.app
MAIN=main

run: ${APP}${EXT}
	#./${APP}
	./${APP}${EXT}/Contents/MacOS/${APP}
${APP}${EXT}: Makefile ./**/*.cpp ./*.cpp ./**/*.h ./*.h
	make
Makefile: ${MAIN}.pro
	qmake ${MAIN}.pro

clean:
	rm .qmake.stash
	rm *.o
	rm moc_*
	rm Makefile
	rm -r *.app/