APP=mundo-virtual
MAIN=main

run: ${APP}.app
	./${APP}
	#./${APP}.app/Contents/MacOS/${APP}
${APP}.app: Makefile *.cpp *.h
	make
Makefile: ${MAIN}.pro
	qmake ${MAIN}.pro

clean:
	rm .qmake.stash
	rm *.o
	rm moc_*
	rm Makefile
	rm -r *.app/