APP=deformaciones	#.app
MAIN=main

run: ${APP}
	./${APP}
	#./${APP}.app/Contents/MacOS/${APP}
${APP}: Makefile ./**/*.cpp ./*.cpp ./**/*.h ./*.h
	make
Makefile: ${MAIN}.pro
	qmake ${MAIN}.pro

clean:
	rm .qmake.stash
	rm *.o
	rm moc_*
	rm Makefile
	rm -r *.app/